version: '3.7'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.3.15-bionic
    restart: always
    networks:
      - traefik
      - default
    ports:
      - "3308:3306"
    volumes:
      - ./.docker/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}

networks:
  traefik:
    external:
      name: ${NETWORK:-local_infra}
