version: '3.7'

services:
  mongo:
    container_name: mongodb
    image: mongo:4.2-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD:-password}
    networks:
      - traefik
    ports:
      - ${DB_EXTERNAL_PORT_MONGO:-27017}:${DB_MONGO_PORT:-27017}
    volumes:
      - ./.docker/mongo/:/data/db

networks:
  traefik:
    external:
      name: ${NETWORK:-local_infra}
